config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "tasks", to: "tasks#index"

  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"


  get    "tasks:id/edit", to: "tasks#edit", as: :task_edit
  patch  "tasks/:id", to: "tasks#update"

  delete "tasks/:id", to: "tasks#destroy"

  get "tasks/:id", to: "tasks#show", as: :task


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to task_path(@task)
  end

private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit a task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>

  <div class="btn btn-success">
    <%= f.label :completed %>
    <%= f.check_box :completed %>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/index.html.erb
<h1>The tasks index</h1>

<% @tasks.each do |task| %>
<ul>
  <li><%= task.title %></li>
  <%= link_to "#{task.title}", task_path(task) %>
</ul>
<% end %>

<%= link_to "create a new task", tasks_new_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <div class="btn btn-success">
    <%= f.label :completed %>
    <%= f.check_box :completed %>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<%= link_to "edit the task", task_edit_path %>


<h2><%= @task.details %></h2>
<p>this task is not completed yet</p>

<%= link_to "Delete", task_path(@task),
      method: :delete,
      data: { confirm: "Are you sure?" } %>

<%= link_to "back to tasks", tasks_path %>